# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-08 01:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vpn_server', '0003_auto_20171107_1750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device_info',
            name='name',
        ),
    ]
